### ISSUE TITLE
About the video demo

### ISSUE THREAD

**Issue by gogo00007** [wy1iu/sphereface#18]
It is said only one image is registered for each person (could be the face detected  for the first time), so in this case can I ask whether it is an open set test demo? E.g. the similarity between the registered face and the test titled one is always larger than the pre-set threshold (recognized as the same person). It seems once the face is detected, the recognition result is always right. Looking forward to your reply.

**Comment by wy1iu** [comment]
Yes, it is indeed an open set test demo, because we do not use any identities in the video as training set. Your understanding about the testing is correct (i.e., one registered face is just for comparing the similarity). 

Also note that our demo is based on frame-by-frame detection and recognition. That is, each frame is processed independently.

**Comment by smajida** [comment]
@wy1iu could you please kindly provide the script which you used to process the video demo?
